; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
board_build.arduino.memory_type = qio_opi
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	arduino-libraries/Arduino_BMI270_BMM150@^1.2.3
	gmarty2000/Buzzer@^1.0.0
	adafruit/Adafruit MMC56x3@^1.0.2
	janelia-arduino/AT42QT@^0.7.2
	stm32duino/STM32duino VL53L8CX@^2.1.0
	workloads/SCServo@^1.0.1
	bodmer/TFT_eSPI@^2.5.43
	milad-nikpendar/initGT911@^1.0.0
